apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    service: nginx
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      serviceAccountName: nginx
      containers:
      - image: quay.io/gspence/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ssl
      version: v1
  template:
    metadata:
      labels:
        app: nginx-ssl
        version: v1
    spec:
      serviceAccountName: nginx
      containers:
      - image: quay.io/gspence/nginx-ssl
        imagePullPolicy: Always
        name: nginx-ssl
        ports:
        - containerPort: 443
        volumeMounts:
        - name: cert
          mountPath: /etc/nginx/certs
      volumes:
      - name: cert
        secret:
          secretName: pass-credential
          items:
          - key: tls.crt
            path: server.crt
          - key: tls.key
            path: server.key
