apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  gatewayClassName: istio
  ${GW_ADDRESSES_YAML}
  listeners:
  - name: http
    hostname: "http.${GWAPI_DOMAIN}"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: edge
    hostname: "edge.${GWAPI_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: edge-credential
        group: ""
    allowedRoutes:
      namespaces:
        from: All
  - name: reencrypt
    hostname: "re.${GWAPI_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: re-credential
        group: ""
    allowedRoutes:
      namespaces:
        from: All
  - name: passthrough
    hostname: "pass.${GWAPI_DOMAIN}"
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: TLSRoute
  - name: http-features
    hostname: "*.hf.${GWAPI_DOMAIN}"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
# This is required or multus will complain
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: istio-cni
  namespace: gwapi
