apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-rewrite
spec:
  parentRefs:
  - name: gateway
  hostnames: ["http-rewrite.hf.${GWAPI_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx
      port: 8000
      filters:
      - type: URLRewrite
        urlRewrite:
          hostname: "http-rewrited.hf.${GWAPI_DOMAIN}"
