# THIS DOESN'T WORK! It's for request headers, not response headers!
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-hsts
spec:
  parentRefs:
  - name: gateway
  hostnames: ["http-hsts.hf.${GWAPI_DOMAIN}"]
  rules:
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: Test123
          value: test
    backendRefs:
    - name: nginx
      port: 8000
