# This should FAIL because there is no reference grant!
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: reference-grant-invalid-test
  namespace: ${GWAPI_NS}
spec:
  parentRefs:
  - name: gateway
    namespace: ${GWAPI_NS}
  hostnames: ["invalid-rg.${GWAPI_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx
      namespace: scope
      port: 8000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: reference-grant-valid-test
  namespace: ${GWAPI_NS}
spec:
  parentRefs:
  - name: gateway
    namespace: ${GWAPI_NS}
  hostnames: ["valid-rg.${GWAPI_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx
      namespace: auto
      port: 8000
---
apiVersion: v1
kind: Namespace
metadata:
  name: auto
---
# Because this is straddling different API version in each setups, use a variable
apiVersion: gateway.networking.k8s.io/${REFERENCE_GRANT_API_VERSION}
kind: ReferenceGrant
metadata:
  name: auto
  namespace: auto
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: ${GWAPI_NS}
  to:
  - group: ""
    kind: Service
