apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: edge
  namespace: ${GWAPI_NS}
spec:
  parentRefs:
  - name: gateway
  hostnames: ["edge.${GWAPI_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx
      port: 8000
