apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: bookinfo-gateway
  namespace: ${GWAPI_NS}
spec:
  gatewayClassName: openshift-gateway
  ${GW_ADDRESSES_YAML}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "book.${GWAPI_DOMAIN}"
    allowedRoutes:
      namespaces:
        from: All
